# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: asahi-scripts.spec
files_to_sync:
  - asahi-scripts.spec
  - .packit.yaml

actions:
  # Fetch the specfile from Rawhide, disable rpmautospec and download config
  post-upstream-clone: "bash -c \"curl -s https://src.fedoraproject.org/rpms/asahi-scripts/raw/main/f/asahi-scripts.spec | sed -e '/^%autochangelog$/d' > asahi-scripts.spec && curl -s --remote-name https://src.fedoraproject.org/rpms/asahi-scripts/raw/main/f/15-update-m1n1.install && curl -s --remote-name https://src.fedoraproject.org/rpms/asahi-scripts/raw/main/f/update-m1n1.sysconfig\""

srpm_build_deps:
  - bash
  - curl
  - sed

jobs:
- job: copr_build
  trigger: commit
  owner: "@asahi"
  project: packit-builds
  targets:
    - fedora-all-aarch64
    - fedora-rawhide-i386
    - fedora-rawhide-ppc64le
    - fedora-rawhide-s390x
    - fedora-rawhide-x86_64

- job: copr_build
  trigger: pull_request
  owner: "@asahi"
  project: packit-builds
  targets:
    - fedora-all-aarch64
    - fedora-rawhide-i386
    - fedora-rawhide-ppc64le
    - fedora-rawhide-s390x
    - fedora-rawhide-x86_64
